### ISSUE TITLE
vsphere-iso crash panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bidetzz** [hashicorp/packer-plugin-vsphere#293]
When filing a bug please include the following headings, if possible. 

#### Overview of the Issue

vsphere-iso is crashing at the end of the packer build.

#### Reproduction Steps

packer init and then packer build.

### Packer Version

Packer version 1.9.1

### Plugin Version and Builders

Please provide the plugin version.

packer-plugin-vsphere v1.2.1

Please select the builder.

- [x] `vsphere-iso`
- [] `vsphere-clone`

### VMware vSphere Version

Please provide the VMware vSphere version.

VMware vSphere version 7.0.3.01400

### Guest Operating System

Having the same error while building windows server 2022 Datacenter and Ubuntu 22.04 LTS

### Simplified Packer Buildfile
```
packer {
  required_plugins {
    vsphere = {
      version = "= v1.2.1"
      source  = "github.com/hashicorp/vsphere"
    }
  }
}

source "vsphere-iso" "linux-ubuntu" {
  vcenter_server = "foo"
  username       = "foo"
  password       = "foo"
  cluster        = "foo"
  vm_name        = "foo"
  storage {
    disk_size    = 40960
    disk_thin_provisioned = "foo"
  }
}

build {
  sources = ["source.vsphere-iso.linux-ubuntu"]
}
```

### Log Fragments and `crash.log` Files

Include appropriate log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log or use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.
<details>
<summary>build log</summary>

```
Build 'vsphere-iso.linux-ubuntu' errored after 7 minutes 22 seconds: unexpected EOF

==> Wait completed after 7 minutes 22 seconds

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso.linux-ubuntu: unexpected EOF

==> Builds finished but no artifacts were created.
panic: runtime error: invalid memory address or nil pointer dereference
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x118d725]
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin:
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: goroutine 212 [running]:
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/driver.(*VirtualMachineDriver).ImportOvfToContentLibrary(0xc0008fc2f0, {{{0xc0001141e0, 0x53}, {0xc000054360, 0x21}, {0x0, 0x0, 0x0}}, {{0x0, 0x0}, ...}, ...})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin:       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/driver/vm.go:841 +0x445
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common.(*StepImportToContentLibrary).importOvfTemplate(0xc000f57c50?, 0xc00019aa00?)
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin:       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/step_import_to_content_library.go:186 +0x107
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common.(*StepImportToContentLibrary).Run(0xc000a90118, {0x2459799?, 0xc000f84b80?}, {0x29a3da8, 0xc000f57c80})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin:       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/step_import_to_content_library.go:149 +0x2e8
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc000f57d40, {0x29a38d8, 0xc000f84b80}, {0x29a3da8, 0xc000f57c80})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin:       github.com/hashicorp/packer-plugin-sdk@v0.4.0/multistep/basic_runner.go:73 +0x2f3
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/iso.(*Builder).Run(0xc000b38800, {0x29a38d8, 0xc000f84b80}, {0x29a64c8?, 0xc000f57c50}, {0x29846e0?, 0xc000c3acc0})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin:       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/iso/builder.go:164 +0x15c3
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc000530680, 0xeacea8?, 0xc000eace8c)
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin:       github.com/hashicorp/packer-plugin-sdk@v0.4.0/rpc/builder.go:120 +0x1e3
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: reflect.Value.call({0xc000510960?, 0xc00050e278?, 0x13?}, {0x2451a45, 0x4}, {0xc000acaef8, 0x3, 0x3?})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin:       reflect/value.go:556 +0x845
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: reflect.Value.Call({0xc000510960?, 0xc00050e278?, 0x0?}, {0xc000e5c6f8, 0x3, 0x3})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin:       reflect/value.go:339 +0xbf
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: net/rpc.(*service).call(0xc0005306c0, 0x0?, 0x0?, 0xc000140240, 0xc000525000, 0x0?, {0x1f55520?, 0xc000eace88?, 0x0?}, {0x1ed4f40, ...}, ...)
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin:       net/rpc/server.go:381 +0x226
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: created by net/rpc.(*Server).ServeCodec
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin:       net/rpc/server.go:478 +0x3fe
2023/07/18 11:07:06 [INFO] (telemetry) ending vsphere-iso.linux-ubuntu
2023/07/18 11:07:06 ui error: Build 'vsphere-iso.linux-ubuntu' errored after 7 minutes 22 seconds: unexpected EOF
2023/07/18 11:07:06 ui:
==> Wait completed after 7 minutes 22 seconds
2023/07/18 11:07:06 machine readable: error-count []string{"1"}
2023/07/18 11:07:06 ui error:
==> Some builds didn't complete successfully and had errors:
2023/07/18 11:07:06 machine readable: vsphere-iso.linux-ubuntu,error []string{"unexpected EOF"}
2023/07/18 11:07:06 ui error: --> vsphere-iso.linux-ubuntu: unexpected EOF
2023/07/18 11:07:06 ui:
==> Builds finished but no artifacts were created.
2023/07/18 11:07:06 /home/foo/.config/packer/plugins/github.com/hashicorp/vsphere/packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64: plugin process exited
2023/07/18 11:07:06 [INFO] (telemetry) Finalizing.
2023/07/18 11:07:06 waiting for all plugin processes to complete...
2023/07/18 11:07:06 /usr/bin/packer: plugin process exited
2023/07/18 11:07:06 /home/foo/.config/packer/plugins/github.com/ethanmdavidson/git/packer-plugin-git_v0.4.2_x5.0_linux_amd64: plugin process exited
2023/07/18 11:07:06 /usr/bin/packer: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
</details>

<details>
<summary>crash.log</summary>

```
2023/07/18 11:07:06 ui: [1;32m==> vsphere-iso.linux-ubuntu: Importing VM OVF template linux-ubuntu-22.04-lts-foo to Content Library 'sfo-w01-lib01' as the item 'linux-ubuntu-22.04-lts-foo' with the description 'Version: foo
==> vsphere-iso.linux-ubuntu: Built on: 2023-07-18 14:59 UTC
==> vsphere-iso.linux-ubuntu: Built by: HashiCorp Packer 1.9.1'...[0m
2023/07/18 11:07:06 ui: [0;32m    vsphere-iso.linux-ubuntu: Closing sessions ....[0m
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 2023/07/18 11:07:06 [WARN] Failed to close REST client session. The session may already be closed: DELETE https://vpshere.foo.com/rest/com/vmware/cis/session: 401 Unauthorized
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: panic: runtime error: invalid memory address or nil pointer dereference
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x118d725]
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: goroutine 212 [running]:
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/driver.(*VirtualMachineDriver).ImportOvfToContentLibrary(0xc0008fc2f0, {{{0xc0001141e0, 0x53}, {0xc000054360, 0x21}, {0x0, 0x0, 0x0}}, {{0x0, 0x0}, ...}, ...})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/driver/vm.go:841 +0x445
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common.(*StepImportToContentLibrary).importOvfTemplate(0xc000f57c50?, 0xc00019aa00?)
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/step_import_to_content_library.go:186 +0x107
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common.(*StepImportToContentLibrary).Run(0xc000a90118, {0x2459799?, 0xc000f84b80?}, {0x29a3da8, 0xc000f57c80})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/step_import_to_content_library.go:149 +0x2e8
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc000f57d40, {0x29a38d8, 0xc000f84b80}, {0x29a3da8, 0xc000f57c80})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.4.0/multistep/basic_runner.go:73 +0x2f3
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/iso.(*Builder).Run(0xc000b38800, {0x29a38d8, 0xc000f84b80}, {0x29a64c8?, 0xc000f57c50}, {0x29846e0?, 0xc000c3acc0})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/iso/builder.go:164 +0x15c3
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc000530680, 0xeacea8?, 0xc000eace8c)
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.4.0/rpc/builder.go:120 +0x1e3
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: reflect.Value.call({0xc000510960?, 0xc00050e278?, 0x13?}, {0x2451a45, 0x4}, {0xc000acaef8, 0x3, 0x3?})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 	reflect/value.go:556 +0x845
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: reflect.Value.Call({0xc000510960?, 0xc00050e278?, 0x0?}, {0xc000e5c6f8, 0x3, 0x3})
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 	reflect/value.go:339 +0xbf
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: net/rpc.(*service).call(0xc0005306c0, 0x0?, 0x0?, 0xc000140240, 0xc000525000, 0x0?, {0x1f55520?, 0xc000eace88?, 0x0?}, {0x1ed4f40, ...}, ...)
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 	net/rpc/server.go:381 +0x226
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: created by net/rpc.(*Server).ServeCodec
2023/07/18 11:07:06 packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64 plugin: 	net/rpc/server.go:478 +0x3fe
2023/07/18 11:07:06 [INFO] (telemetry) ending vsphere-iso.linux-ubuntu
2023/07/18 11:07:06 ui error: [1;31mBuild 'vsphere-iso.linux-ubuntu' errored after 7 minutes 22 seconds: unexpected EOF[0m
2023/07/18 11:07:06 ui: 
==> Wait completed after 7 minutes 22 seconds
2023/07/18 11:07:06 machine readable: error-count []string{"1"}
2023/07/18 11:07:06 ui error: 
==> Some builds didn't complete successfully and had errors:
2023/07/18 11:07:06 machine readable: vsphere-iso.linux-ubuntu,error []string{"unexpected EOF"}
2023/07/18 11:07:06 ui error: --> vsphere-iso.linux-ubuntu: unexpected EOF
2023/07/18 11:07:06 ui: 
==> Builds finished but no artifacts were created.
2023/07/18 11:07:06 /home/foo/.config/packer/plugins/github.com/hashicorp/vsphere/packer-plugin-vsphere_v1.2.1_x5.0_linux_amd64: plugin process exited
2023/07/18 11:07:06 [INFO] (telemetry) Finalizing.
2023/07/18 11:07:06 waiting for all plugin processes to complete...
2023/07/18 11:07:06 /usr/bin/packer: plugin process exited
2023/07/18 11:07:06 /home/foo/.config/packer/plugins/github.com/ethanmdavidson/git/packer-plugin-git_v0.4.2_x5.0_linux_amd64: plugin process exited
2023/07/18 11:07:06 /usr/bin/packer: plugin process exited
```
</details>

**Comment by t106362512** [comment]
Having the same error while building centos 8-stream.

- vSphere 7.0.3
- Packer 1.9.4
- packer-vsphere-plugin 1.2.1

**Comment by t106362512** [comment]
This error message confuses me...

This error occurred because the permissions I granted only applied to the data center, not the global permission.

Refer https://github.com/hashicorp/packer-plugin-vsphere/issues/57#issuecomment-941580589

**Comment by tenthirtyam** [comment]
@bidetzz Based on the logs I can see that you were using my project and it's failing cloning to the content library.

This is due to the lack of global permissions that are required for the vSphere content library.

Refer to: https://vmware-samples.github.io/packer-examples-for-vsphere/getting-started/privileges/#required-privileges

**Comment by bidetzz** [comment]
@tenthirtyam yep that was it ! thank you for your help !
